### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by Maciej916** [waylaidwanderer/node-opskins-tradeoffer-manager#5]
I would be better to change this line from:
`throw new Error(data.message);`
to:
`throw data.message;`
for better error handling on try catch because now you need to acces this by `err.error.message` instead of `err.message` if im wrong correct me.

https://github.com/waylaidwanderer/node-opskins-tradeoffer-manager/blob/5da65daaddb04fc79d25f82430db78f79691a370/index.js#L145

**Comment by waylaidwanderer** [comment]
I use the airbnb style guide which includes this rule: https://eslint.org/docs/rules/no-throw-literal

I believe using `err.message` should still work.
